version: '3.8'

services:
  # expense-shared-modules:
  #   extends:
  #     file: ./docker-compose.${COMPOSE_ENV:-local}.yaml
  #     service: expense-shared-modules

  expense-nginx:
    extends:
      file: ./docker-compose.${COMPOSE_ENV:-local}.yaml
      service: expense-nginx

  expense-postgres:
    extends:
      file: ./docker-compose.${COMPOSE_ENV:-local}.yaml
      service: expense-postgres

  expense-backend:
    extends:
      file: ./docker-compose.${COMPOSE_ENV:-local}.yaml
      service: expense-backend
  
  expense-frontend:
    extends:
      file: ./docker-compose.${COMPOSE_ENV:-local}.yaml
      service: expense-frontend

  expense-pg-admin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root

    volumes:
      - ./.data/pgadmin:/var/lib/pgadmin

    ports: 
     - "5050:80"
    
    depends_on:
      - expense-postgres

volumes:
  # postgres:
  mongodb:
  backend_node_modules:
  frontend_node_modules:
  # mobile_app_node_modules: